//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ferme
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDENES_COMPRA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ORDENES_COMPRA()
        {
            this.ORDENES_COMPRA_DETALLE = new HashSet<ORDENES_COMPRA_DETALLE>();
        }
    
        public long ID { get; set; }
        public long ID_PROVEEDOR { get; set; }
        public Nullable<long> ID_TRABAJADOR { get; set; }
        public string ESTADO { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
        public System.DateTime FECHA_RECEPCION { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDENES_COMPRA_DETALLE> ORDENES_COMPRA_DETALLE { get; set; }
        public virtual TRABAJADORES TRABAJADORES { get; set; }
        public virtual PROVEEDORES PROVEEDORES { get; set; }
    }
}
