//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ferme
{
    using System;
    using System.Collections.Generic;
    
    public partial class PASSWORD_RESETS
    {
        public string EMAIL { get; set; }
        public string TOKEN { get; set; }
        public Nullable<System.DateTime> CREATED_AT { get; set; }
    }
}
