//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ferme
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUCTOS()
        {
            this.BOLETAS_DETALLE = new HashSet<BOLETAS_DETALLE>();
            this.ORDENES_COMPRA_DETALLE = new HashSet<ORDENES_COMPRA_DETALLE>();
            this.PRODUCTO_FAVORITOS = new HashSet<PRODUCTO_FAVORITOS>();
            this.PRODUCTO_IMAGENES = new HashSet<PRODUCTO_IMAGENES>();
            this.REGISTROS_STOCK = new HashSet<REGISTROS_STOCK>();
        }
    
        public long ID { get; set; }
        public string CODIGO { get; set; }
        public long ID_TIPOPRODUCTO { get; set; }
        public long ID_FAMILIAPRODUCTO { get; set; }
        public long ID_PROVEEDOR { get; set; }
        public string NOMBRE { get; set; }
        public string DESCRIPCION { get; set; }
        public int PRECIO { get; set; }
        public Nullable<System.DateTime> FECHA_VENCIMIENTO { get; set; }
        public int STOCK { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BOLETAS_DETALLE> BOLETAS_DETALLE { get; set; }
        public virtual FAMILIAS_PRODUCTO FAMILIAS_PRODUCTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDENES_COMPRA_DETALLE> ORDENES_COMPRA_DETALLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCTO_FAVORITOS> PRODUCTO_FAVORITOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCTO_IMAGENES> PRODUCTO_IMAGENES { get; set; }
        public virtual PROVEEDORES PROVEEDORES { get; set; }
        public virtual TIPOS_PRODUCTO TIPOS_PRODUCTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REGISTROS_STOCK> REGISTROS_STOCK { get; set; }
    }
}
